### ISSUE TITLE
sendCommand doesn't seem to work

### ISSUE THREAD

**Issue by LiorArbel** [loloof64/React-Native-Stockfish-Android#1] opened 2022-07-26 13:17 UTC
Hey, first of all thank you very much for creating this repository!!
I'm trying to use it, after configuring everything and writing the code as follows:

```
useEffect(() => {
    const eventEmitter = new NativeEventEmitter(NativeModules.ReactNativeStockfishChessEngine);
    const eventListener = eventEmitter.addListener('stockfish-output', (line) => {
      console.log("Stockfish output: " + line);
    });
    mainLoop(); // starts the engine process.
    setTimeout(() => {
      sendCommand("uci\n");

    }, 1000);
    // sendCommand("isReady\n");
  }, []);
```

All I get is ` LOG  Stockfish output: Stockfish 15 by the Stockfish developers (see AUTHORS file)` and no responses anymore from the listener.
I tried many different types of UCI commands, and I tried `async await`ing the `mainLoop` and `sendCommand` in many different ways, nothing seems to work.

Would really appreciate your help, thanks in advance!!

**Comment by LiorArbel** [comment] 2022-07-26 13:56
Running the example project, I got responses for the first time I pressed "compute best move" but afterwards it seemed to hang again.
Similar thing happened to me in my project, between a lot of tries one time I got a response "uciok" (without changing anything in my code) but couldn't reproduce, and again afterwards it was still hanging

**Comment by loloof64** [comment] 2022-07-26 19:57
Hi ! First, thanks for your interest in this repository.

Maybe your code does not work because the following functions are asynchronous : 
* mainLoop()
* sendCommand()
whereas you are calling them in a synchronous way.

(So, you may want to call async/await, or use then/catch clauses with their calls.)

Please, let me know if it is the cause of your issue.

Also, of course, don't forget to call shutdownStockfish() when you've finished, which is also asynchronous.

**Comment by loloof64** [comment] 2022-07-26 22:48
Oh, my bad. I've just seen that you also used async/await. So it's really difficult to say from where the bug can come from.
Could you share at least your attempt with async/await, as well as
* the version of NodeJs ?
* the version of Ndk ?
* the version of CMake ?

Also, do copying the code from the example folder works ?

Sorry if this does not help so much, but from my side I've managed to run the example again.

(Apart from the installed tools and ndk, I'm using NodeJS 16)

**Comment by loloof64** [comment] 2023-05-07 22:16
Closing as did not get any response since one year ago.

**Closed as completed** 2023-05-07 22:15 UTC
